##LogisticRegression Assignment Field Goal
goal = read.csv(file.choose())
head(goal)
tail(goal)
summary(goal)
successes = factor(goal$success)
summary(goal)
goallogit1 = glm(success ~ yard + week, data = goal, family = "binomial")
summary(goallogit1)
goallogit2 = glm(success ~ yard, data = goal, family = "binomial")
summary(goallogit2)
newdat= data.frame(yard=seq(min(goal$yard), max(goal$yard),len=100))
newdat$success = predict(goallogit2, newdata=newdat, type="response")
plot(goal$yard,goal$success)
summary(goal$success)
lines(success ~ yard, newdat, col="green4", lwd=2)
install.packages(popbio)
library(popbio)
logi.hist.plot(goal$yard,goal$success,boxp=FALSE,type="hist",col="gray")
